### ISSUE TITLE
[request] wr table

### ISSUE THREAD

**Issue by rlgtd3** [TotallyMehis/SM-OpenTimer#2]
Can you make separate submenu for each style in !wr? Thanks

**Comment by TotallyMehis** [comment]
I'm not sure what you mean by this, because you can just use !wr <style> <mode> <run>, etc.

E.g,

!wr w main - Displays W-Only runs from Main.
!wr bonus1 hsw 400 - Displays all Bonus 1 HSW 400vel runs.
