### ISSUE TITLE
List of issues I have found.

### ISSUE THREAD

**Issue by bletzkarn** [TotallyMehis/SM-OpenTimer#3]
Replay bots will not spawn if there isn't a CT present. This is a problem because many bhop maps don't have CT spawns as T is the default spawn.

When setting start/end zone - it's possible to get a time of 0:00:00 where the replay bot will stand still. Deleting he top will not delete the replay bot however.

!bonus - timer zone not on by default :( Have to type !b to get it to start the time.

As a feature if you restart a run Practise mode should be turned off. Can't tell you how many times I started a run.. only to realise I was on P mode.

Otherwise I love this timer!! only good bhop timer currently!! (kzmod bhop is SHIT) and zipcore doesn't have replay bots.

**Comment by NetorareBoyFriend** [comment]
// Determine what team we should put the runners in when map starts.
	// Bots go to the other team.
	int num_ct;
	int num_t;
	
	ent = -1;
	while ( (ent = FindEntityByClassname( ent, "info_player_counterterrorist" )) != -1 ) num_ct++;
	
	ent = -1;
	while ( (ent = FindEntityByClassname( ent, "info_player_terrorist" )) != -1 ) num_t++;
	
#if defined DEV
	PrintToServer( CONSOLE_PREFIX..."Found %i CT spawns and %i T spawns.", num_ct, num_t );
#endif
	
	
	Handle hCvar_HumanTeam = FindConVar( "mp_humanteam" );
	Handle hCvar_BotTeam = FindConVar( "bot_join_team" );
	
	if ( hCvar_HumanTeam == null )
		SetFailState( CONSOLE_PREFIX..."Unable to find cvar handle for mp_humanteam!" );
	
	if ( hCvar_BotTeam == null )
		SetFailState( CONSOLE_PREFIX..."Unable to find cvar handle for bot_join_team!" );
	
	if ( !num_t || !num_ct )
	{
		SetConVarString( hCvar_HumanTeam, "any", true );
		SetConVarString( hCvar_BotTeam, "any", true );
		
		
		g_iPreferredTeam = ( !num_ct ) ? CS_TEAM_T : CS_TEAM_CT;
	}
	else
	{
		SetConVarString( hCvar_HumanTeam, "ct", true );
		SetConVarString( hCvar_BotTeam, "t", true );
	}


delete it.
it's about bot's team.

**Comment by TotallyMehis** [comment]
The replay bots not spawning is because you have not set the command bot_join_after_player to 0. I'll add this to the readme.

If you don't disable the keyhint text, it will display if you're in practice mode.

I'm working on another thing right now, but I'll see what I can do.
