### ISSUE TITLE
List of issues.

### ISSUE THREAD

**Issue by bletzkarn** [TotallyMehis/SM-OpenTimer#4]
Easy to replicate issues:

On auto-bhop settings it is not possible to jump off of ladders (press jump while on the ladder) Not a huge deal but makes some maps difficult to beat.

When a bot is added after getting a record. All players are reset to the start. Some of the players games will crash. (Possible CFG issue)

Hard to replicate issues: (totally possible these are server issues, we're only running opentimer plugin atm)

- Client crash (not server). Some people have their games cash, not everyone. The newest version of the timer seems less stable than the old version.

- Sometimes not poissble to join a team. Need to go into spectate, then type !r to get on a team.

**Comment by bletzkarn** [comment]
At the moment we just trying to get the timer stable with replay bots - no crashes, restarts or spawn issues.

**Comment by bletzkarn** [comment]
It's not our server. 1.5 version crashes clients game.

**Comment by TotallyMehis** [comment]
Just pushed out an update which should fix client crashing and autobhop.
I'll look into the other things.
